# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weddings' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weddings
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
	pod 'Firebase/Storage'
  pod "RSLoadingView"
  pod 'Kingfisher', '~> 4.0'
  pod 'SnackView', '~> 1.0.2'
end
